---
title: "Sandbox"
format: html
---

```{r}
library(tidyverse)

# Grab data from GH
vesuvius <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-05-13/vesuvius.csv') |>
  select(-type, -area) |>  # is always "earthquake" and "Mount Vesuvius" 
  mutate(time_unix = time - ymd_hms("1970-01-01 00:00:00"),
         obs_day = as.Date(time)) |>
  filter(obs_day >= ymd("2013-01-01")) # data is very sparse before this

```

```{r}
skimr::skim(vesuvius)
```


## Over Time
```{r}
vesuvius |> 
  ggplot(aes(x = time, y = depth_km)) +
  geom_point() +
  scale_x_datetime(date_breaks = "1 year", date_labels =  "%Y")
```

Observations:

- I see an event in 

```{r}
vesuvius |>
  ggplot(aes(x = depth_km, y = duration_magnitude_md)) +
  geom_point() 

```

## Frequency
```{r}
# Fill in missing dates
all_days <- tibble(
  obs_day = seq.Date(from = ymd("2013-01-01"), to = ymd("2024-12-31"), by = "day")
  )

# for date breaks
breaks <- as.Date(ymd(c("2013-01-01",
                        "2014-01-01", 
                        "2015-01-01",
                        "2016-01-01",
                        "2017-01-01",
                        "2018-01-01",
                        "2019-01-01",
                        "2020-01-01",
                        "2021-01-01",
                        "2022-01-01",
                        "2023-01-01",
                        "2024-01-01",
                        "2025-01-01")))

vesuvius_agg <- vesuvius |>
  summarize(n = n(),
            .by = obs_day) |>
  right_join(all_days, by = "obs_day") |>
  mutate(n = replace_na(n,0)) |>
  arrange(desc(n)) |>
  mutate(top_ten = case_when(
    row_number() <= 10 ~ "top",
    row_number() > 10 ~ "not top"))

# set up our colors
color_list <- c("top" = "yellow",
  "not top" = "grey")

vesuvius_agg |>
  ggplot(aes(x = obs_day, y = n)) +
  geom_col(aes(fill = top_ten)) +
  scale_fill_manual(values = color_list) +
  theme_dark() +
  labs(y = "# of Earthquakes",
       x = "Date",
       title = "Earthquake Activity Near Mt Vesuvius Over Time") +
  scale_x_date(breaks = breaks,
               date_labels = "%Y") +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) +
  guides(fill = "none")

```

```{r}
vesuvius |> 
  filter(obs_day == ymd("2013-02-24")) 
```

