---
title: "Tidy Tuesday - Vesuvius Eruptions"
author: "Simon"
format: html
---

```{r}
library(tidyverse)
library(ggtext)

# Grab data from GH
vesuvius <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-05-13/vesuvius.csv') |>
  select(-type, -area) |>  # is always "earthquake" and "Mount Vesuvius" 
  mutate(time_unix = time - ymd_hms("1970-01-01 00:00:00"),
         obs_day = as.Date(time)) |>
  filter(obs_day >= ymd("2013-01-01")) # data is very sparse before this
```

```{r}
# Fill in missing dates
all_days <- tibble(
  obs_day = seq.Date(from = ymd("2013-01-01"), to = ymd("2024-12-31"), by = "day")
  )

# for date breaks
breaks <- as.Date(ymd(c("2013-01-01",
                        #"2014-01-01", 
                        "2015-01-01",
                        #"2016-01-01",
                        "2017-01-01",
                        #"2018-01-01",
                        "2019-01-01",
                        #"2020-01-01",
                        "2021-01-01",
                        #"2022-01-01",
                        "2023-01-01",
                        #"2024-01-01",
                        "2025-01-01")))

vesuvius_agg <- vesuvius |>
  summarize(n = n(),
            .by = obs_day) |>
  right_join(all_days, by = "obs_day") |>
  mutate(n = replace_na(n,0)) |>
  arrange(desc(n)) |>
  mutate(top_ten = case_when(
    row_number() <= 10 ~ "top",
    row_number() > 10 ~ "not top"))

# set up our colors
pop_color <- "orange"
color_list <- c("top" = pop_color,
  "not top" = "grey")

daily_plot <- vesuvius_agg |>
  ggplot(aes(x = obs_day, y = n)) +
  geom_col(aes(fill = top_ten)) +
  geom_text(data = ~ filter(.x, top_ten == "top"), 
            aes(label = obs_day),
            size = 3,
            hjust = -.1,
            angle = 10,
            color = pop_color) +
  scale_fill_manual(values = color_list) +
  theme_dark() +
  labs(y = "# of Earthquakes",
       x = "Date",
       title = "Earthquake Activity Near Mt Vesuvius Over Time",
       subtitle = "<span style = 'color: DarkOrange;'>Top Ten Most Active Days</span> ",
       alt = "A bar plot of with the number of daily earthquakes near Mt. Vesuvius from 2013 to 2025. The top ten most active days are colored orange and they range from about 50 earthquakes to about 150 earthquakes. The rest of the days are in grey and they are much lower, mostly around 1 or 2.") +
  scale_x_date(breaks = breaks,
               date_labels = "%Y") +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.subtitle = ggtext::element_markdown()) +
  guides(fill = "none")

daily_plot
```


```{r}
ggsave("vesuvius.png", path = "~/DsSandbox/", plot = daily_plot, device = "png", height = 5, width = 9)
```

